name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Install All Dependencies
      run: |
        $commit_message=$(git log -1 --pretty=%B)
        if ($commit_message -like '*action*') {
          pip install pipreqs
          pipreqs .
          ls
          Get-Content requirements.txt
          pip install -r requirements.txt
        } else {
          Write-Host "Commit message does not contain the required keyword. Skipping execution."
        }
        
    - name: Check Commit Message and Execute
      run: |
        $commit_message=$(git log -1 --pretty=%B)
        if ($commit_message -like '*action*') {
          cd backend/scrapy-digemid/                       
          python __main2__.py      
        } else {
          Write-Host "Commit message does not contain the required keyword. Skipping execution."
        }

        